spring.application.name=ticket-booking-system
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.mvc.problemdetails.enabled=true

spring.web.resources.static-locations=classpath:/static/